package com.theladders.solid.dip;

import java.util.List;

public interface BasicCriteria
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setOrderByClause(String orderByClause);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public String getOrderByClause() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setDistinct(boolean distinct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public boolean isDistinct();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public List<ExtendedCriteria> getOredCriteria() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void or(ExtendedCriteria someCriteria) ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public ExtendedCriteria or() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public ExtendedCriteria createExtendedCriteria() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public ExtendedCriteria createExtendedCriteriaInternal() ;

    public void mostRecentlyRecommendedComeFirst();

}