package com.theladders.solid.dip;

import java.util.List;

public interface Datum
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setOrderByClause(String orderByClause);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public String getOrderByClause() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setDistinct(boolean distinct);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public boolean isDistinct();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public List<Criteria> getOredCriteria() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void or(Criteria someCriteria) ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public Criteria or() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public Criteria createCriteria() ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public Criteria createCriteriaInternal() ;

}