package com.theladders.solid.dip;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  abstract class GeneratedCriteria implements Criteria
  {
    protected List<Map<String, Object>> criteriaWithSingleValue;

    protected List<Map<String, Object>> criteriaWithListValue;


    protected GeneratedCriteria()
    {
      super();
      criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
      criteriaWithListValue = new ArrayList<Map<String, Object>>();
    }


    public void addCriterion(String condition,
                                Object value,
                                String property)
    {
      if (value == null)
      {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map<String, Object> map = new HashMap<String, Object>();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }


    public void addCriterion(String condition,
                                List<? extends Object> values,
                                String property)
    {
      if (values == null || values.size() == 0)
      {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map<String, Object> map = new HashMap<String, Object>();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }


    public Criteria andSubscriberIdEqualTo(Integer value)
    {
      addCriterion("subscriber_id =", value, "subscriberId");
      return  null;
    }


    public Criteria andSuggestedArticleSourceIdEqualTo(Integer value)
    {
      addCriterion("suggested_article_source_id =", value, "suggestedArticleSourceId");
      return  null;
    }


    public Criteria andSuggestedArticleStatusIdIn(List<Integer> values)
    {
      addCriterion("suggested_article_status_id in", values, "suggestedArticleStatusId");
      return  null;
    }
  }
