package com.theladders.solid.dip;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  abstract class GeneratedCriteria implements ExtendedCriteria
  {
    protected List<Map<String, Object>> criteriaWithSingleValue;

    protected List<Map<String, Object>> criteriaWithListValue;


    protected GeneratedCriteria()
    {
      super();
      criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
      criteriaWithListValue = new ArrayList<Map<String, Object>>();
    }


    public void addCriterion(String condition,
                                Object value,
                                String property)
    {
      if (value == null)
      {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map<String, Object> map = new HashMap<String, Object>();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }


    public void addCriterion(String condition,
                                List<? extends Object> values,
                                String property)
    {
      if (values == null || values.size() == 0)
      {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map<String, Object> map = new HashMap<String, Object>();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }


    public ExtendedCriteria forSubscriber(Subscriber aSubscriber)
    {
      addCriterion("subscriber_id =", aSubscriber.getID(), "subscriberId");
      return  null;
    }


    public ExtendedCriteria fromHTPConsultant()
    {
      addCriterion("suggested_article_source_id =", 1, "suggestedArticleSourceId");
      return  null;
    }


    public ExtendedCriteria newOrViewed()
    {
      addCriterion("suggested_article_status_id in", Arrays.asList(1, 2), "suggestedArticleStatusId");
      return  null;
    }

  }
