package com.theladders.solid.dip;

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table suggested_article
   *
   * @mbggenerated do_not_delete_during_merge Fri Dec 03 17:06:47 EST 2010
   */
  public class SuggestedArticleCriteria extends GeneratedCriteria
  {

    protected SuggestedArticleCriteria()
    {
      super();
    }
  }
