package com.theladders.solid.dip;

import java.util.ArrayList;
import java.util.List;

public class SuggestedArticleExample implements Datum
{
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 201
   */
  protected List<Criteria> oredCriteria;


  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public SuggestedArticleExample() {
    oredCriteria = new ArrayList<>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public void or(Criteria someCriteria) {
    oredCriteria.add(someCriteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public Criteria or() {
    Criteria someCriteria = createCriteriaInternal();
    oredCriteria.add(someCriteria);
    return someCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public Criteria createCriteria() {
    Criteria internalCriteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(internalCriteria);
    }
    return internalCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public Criteria createCriteriaInternal() {
    Criteria suggestedArticleCriteria = new SuggestedArticleCriteria();
    return suggestedArticleCriteria;
  }
}
