package com.theladders.solid.dip;

import java.util.ArrayList;
import java.util.List;

public class SuggestedArticleExample implements BasicCriteria
{
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 201
   */
  protected List<ExtendedCriteria> oredCriteria;


  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public SuggestedArticleExample() {
    oredCriteria = new ArrayList<>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public List<ExtendedCriteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public void or(ExtendedCriteria someCriteria) {
    oredCriteria.add(someCriteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public ExtendedCriteria or() {
    ExtendedCriteria someCriteria = createExtendedCriteriaInternal();
    oredCriteria.add(someCriteria);
    return someCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public ExtendedCriteria createExtendedCriteria() {
    ExtendedCriteria internalCriteria = createExtendedCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(internalCriteria);
    }
    return internalCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table suggested_article
   *
   * @mbggenerated Fri Dec 03 17:06:47 EST 2010
   */
  public ExtendedCriteria createExtendedCriteriaInternal() {
    ExtendedCriteria suggestedArticleCriteria = new SuggestedArticleCriteria();
    return suggestedArticleCriteria;
  }

  public void mostRecentlyRecommendedComeFirst()
  {
    setOrderByClause("create_time desc");
  }
}
